In [1]:
import torch
import torch.nn as nn

In [2]:
input_size = 5
hidden_size = 8

In [3]:
inputs = torch.Tensor(1,10,5)

In [4]:
cell = nn.RNN(input_size, hidden_size, batch_first=True)

In [5]:
outputs, _status = cell(inputs)

In [6]:
print(outputs.shape)

torch.Size([1, 10, 8])


In [7]:
print(outputs)

tensor([[[-0.2985,  0.3168, -0.0427, -0.4266,  0.0092, -0.2085, -0.0138,
          -0.0740],
         [ 0.0304,  0.2660, -0.2100, -0.2240,  0.1528, -0.2700,  0.1026,
           0.0520],
         [-0.1066,  0.4430, -0.1094, -0.2017,  0.0866, -0.2067,  0.0356,
           0.0128],
         [-0.0384,  0.3885, -0.1875, -0.2189,  0.1125, -0.2296,  0.0503,
           0.0290],
         [-0.0637,  0.4173, -0.1774, -0.2026,  0.0953, -0.2291,  0.0239,
           0.0146],
         [-0.0510,  0.4082, -0.1882, -0.2077,  0.0943, -0.2326,  0.0243,
           0.0086],
         [-0.0542,  0.4121, -0.1863, -0.2027,  0.0915, -0.2327,  0.0187,
           0.0063],
         [-0.0533,  0.4107, -0.1873, -0.2045,  0.0906, -0.2329,  0.0184,
           0.0046],
         [-0.0533,  0.4105, -0.1873, -0.2037,  0.0905, -0.2331,  0.0177,
           0.0045],
         [-0.0535,  0.4105, -0.1872, -0.2041,  0.0902, -0.2331,  0.0176,
           0.0041]]], grad_fn=<TransposeBackward1>)


In [9]:
print(_status)

tensor([[[-0.0535,  0.4105, -0.1872, -0.2041,  0.0902, -0.2331,  0.0176,
           0.0041]]], grad_fn=<StackBackward>)


In [10]:
cell = nn.RNN(input_size = 5, hidden_size = 8, num_layers = 2, batch_first=True)

In [11]:
outputs, _status = cell(inputs)

In [12]:
print(outputs)

tensor([[[ 0.3047,  0.0771, -0.4687, -0.0850, -0.3373, -0.5497, -0.1083,
          -0.0773],
         [ 0.4033,  0.0250, -0.5381,  0.0302, -0.5289, -0.6673, -0.1843,
          -0.2691],
         [ 0.4577,  0.0503, -0.4605,  0.0639, -0.6410, -0.6416, -0.2135,
          -0.3317],
         [ 0.4583,  0.0859, -0.4357,  0.0861, -0.6843, -0.5947, -0.2502,
          -0.3656],
         [ 0.4672,  0.0930, -0.4178,  0.0782, -0.7021, -0.5662, -0.2355,
          -0.3802],
         [ 0.4548,  0.1045, -0.4156,  0.0788, -0.7103, -0.5535, -0.2472,
          -0.3795],
         [ 0.4591,  0.0994, -0.4182,  0.0797, -0.7132, -0.5468, -0.2405,
          -0.3840],
         [ 0.4566,  0.1047, -0.4173,  0.0766, -0.7146, -0.5466, -0.2451,
          -0.3816],
         [ 0.4578,  0.1018, -0.4191,  0.0778, -0.7150, -0.5455, -0.2419,
          -0.3838],
         [ 0.4569,  0.1037, -0.4186,  0.0770, -0.7153, -0.5460, -0.2439,
          -0.3826]]], grad_fn=<TransposeBackward1>)


In [13]:
print(_status)

tensor([[[-0.2664,  0.4724,  0.6057, -0.4442,  0.5747,  0.6582,  0.2920,
           0.0889]],

        [[ 0.4569,  0.1037, -0.4186,  0.0770, -0.7153, -0.5460, -0.2439,
          -0.3826]]], grad_fn=<StackBackward>)
