In [13]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [25]:
x_train = [[1, 2, 1],
           [1, 3, 2],
           [1, 3, 4],
           [1, 5, 5],
           [1, 7, 5],
           [1, 2, 5],
           [1, 6, 6],
           [1, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [27]:
x_test = torch.FloatTensor([[2,1,1],[3,1,2],[3,3,4]])
y_test = torch.LongTensor([2,2,2])

In [18]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.max(1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [19]:
class SoftmaxClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,3)
  def forward(self, x):
    return self.linear(x)

In [20]:
model = SoftmaxClassifier()

In [21]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.1)

In [22]:
def train(model, optimizer, x_train, y_train):
  ep = 20
  for epoch in range(ep+1):
    prediction = model(x_train)
    cost = F.cross_entropy(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print(f'epoch: {epoch}/{ep} cost: {cost.item():.4f}')

In [32]:
def test(model, optimizer, x_test, y_test):
  prediction = model(x_test)
  predicted_classes = prediction.max(1)[1]
  print((predicted_classes))
  correct = (predicted_classes == y_test).sum().item()
  cost = F.cross_entropy(prediction, y_test)

  print(f'acc: {correct/len(y_test)}% cost: {cost.item():.4f}')

In [33]:
train(model, optimizer, x_train, y_train)

epoch: 0/20 cost: 0.8133
epoch: 1/20 cost: 0.8103
epoch: 2/20 cost: 0.8073
epoch: 3/20 cost: 0.8044
epoch: 4/20 cost: 0.8016
epoch: 5/20 cost: 0.7987
epoch: 6/20 cost: 0.7960
epoch: 7/20 cost: 0.7932
epoch: 8/20 cost: 0.7905
epoch: 9/20 cost: 0.7879
epoch: 10/20 cost: 0.7853
epoch: 11/20 cost: 0.7827
epoch: 12/20 cost: 0.7802
epoch: 13/20 cost: 0.7777
epoch: 14/20 cost: 0.7752
epoch: 15/20 cost: 0.7728
epoch: 16/20 cost: 0.7704
epoch: 17/20 cost: 0.7680
epoch: 18/20 cost: 0.7657
epoch: 19/20 cost: 0.7634
epoch: 20/20 cost: 0.7611


In [34]:
test(model, optimizer, x_test, y_test)

tensor([2, 2, 2])
acc: 1.0% cost: 0.1034


# Data Preprocessing

In [35]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [36]:
mu = x_train.mean(dim=0)
mu

tensor([84.8000, 84.6000, 83.6000])

In [37]:
sigma = x_train.std(dim=0)
sigma

tensor([11.0544, 12.2393, 12.5419])

In [38]:
norm_x_train = (x_train-mu)/sigma

In [39]:
print(norm_x_train)

tensor([[-1.0674, -0.3758, -0.6857],
        [ 0.7418,  0.2778,  0.7495],
        [ 0.3799,  0.5229, -0.2870],
        [ 1.0132,  1.0948,  1.3076],
        [-1.0674, -1.5197, -1.0844]])


In [50]:
def train(model, optimizer, x_train, y_train):
  ep = 20
  for epoch in range(ep+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)  #regression

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print(f'epoch: {epoch}/{ep} cost: {cost.item():.4f}')

In [51]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)
  def forward(self,x):
    return self.linear(x)

In [52]:
model = MultivariateLinearRegressionModel()
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

In [53]:
train(model, optimizer, norm_x_train, y_train)

epoch: 0/20 cost: 29780.7461
epoch: 1/20 cost: 18916.3164
epoch: 2/20 cost: 12062.8711
epoch: 3/20 cost: 7707.6470
epoch: 4/20 cost: 4929.9023
epoch: 5/20 cost: 3155.1011
epoch: 6/20 cost: 2020.1207
epoch: 7/20 cost: 1293.9847
epoch: 8/20 cost: 829.3112
epoch: 9/20 cost: 531.9131
epoch: 10/20 cost: 341.5529
epoch: 11/20 cost: 219.6921
epoch: 12/20 cost: 141.6700
epoch: 13/20 cost: 91.7052
epoch: 14/20 cost: 59.6978
epoch: 15/20 cost: 39.1842
epoch: 16/20 cost: 26.0274
epoch: 17/20 cost: 17.5798
epoch: 18/20 cost: 12.1469
epoch: 19/20 cost: 8.6445
epoch: 20/20 cost: 6.3782
