In [ ]:
import numpy as np
l = [1,2,3]
array = np.array(l)

print(array)
print(array.size)
print(array.dtype)
print(array[2])

[1 2 3]
3
int64
3


In [ ]:
# 0부터 3까지의 배열 만들기
arr = np.arange(4)
print(arr)

# 1부터 3까지의 배열 만들기
arr = np.arange(1,4)
print(arr)

#0으로 초기화
arr2 = np.zeros((4,4), dtype=float)
print(arr2)

# 1로 초기화, 문자열도 가능
arr3 = np.ones((3,3), dtype=str)
print(arr3)

#0부터 9까지 랜덤하게 초기화된 배열 만들기
arr4 = np.random.randint(0,10,(3,3))
print(arr4)

#평균이 0이고, 표준편차가 1인 표준 정규를 띄는 배열
arr5 = np.random.normal(0,1, (3,3))
print(arr5)

[0 1 2 3]
[1 2 3]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[[5 1 0]
 [3 0 8]
 [4 9 8]]
[[-0.60384415 -0.72076449  0.65299405]
 [-0.12879155  0.52771575 -0.7546787 ]
 [-0.17120311  0.65473393 -0.68268341]]


In [3]:
#배열 합치기
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate([arr1, arr2])
print(arr3.shape)
print(arr3)
print(arr1+arr2)
print(arr3+1)

(6,)
[1 2 3 4 5 6]
[5 7 9]
[2 3 4 5 6 7]


In [ ]:
# 배열 형태 바꾸기  ###중요###
arr1 = np.array([1,2,3,4])
arr2 = arr1.reshape((-1,2))
arr2


array([[1, 2],
       [3, 4]])

In [ ]:
arr1 = np.arange(4).reshape(1,4)
arr2 = np.arange(8).reshape(2,4)


# arr3 = np.vstack([arr1,arr2])
arr3 = np.concatenate([arr2,arr1],axis=0)
print(arr3)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]]


In [ ]:
#배열 나누기
arr = np.arange(8).reshape(2,4)
# left, right = np.split(arr, [1], axis=0)
left, right = np.split(arr, [2], axis=1)
print(left.shape)
print(right.shape)
print(arr)
print(left)
print(right)

(2, 2)
(2, 2)
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]]
[[2 3]
 [6 7]]


In [ ]:
#기본연산
arr = np.random.randint(1,10, size=4).reshape(2,2)
print(arr)
result= arr*10
print(result)

[[3 4]
 [2 1]]
[[30 40]
 [20 10]]


In [ ]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(2)
arr3 = arr1+arr2
print(arr3)

[[0 2]
 [2 4]]


In [ ]:
arr1 = np.arange(8).reshape(2,4)
arr2 = np.arange(8).reshape(2,4)
arr3 = np.concatenate([arr1,arr2],axis=0)
arr4 = np.arange(4).reshape(1,4)

print(arr3+arr4)

[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 0  2  4  6]
 [ 4  6  8 10]]


In [ ]:
#마스킹 연산
arr1 = np.arange(16).reshape(4,4)
arr2 = arr1<10
print(arr2)

#10보다 작은 원소만 선택해서 100으로만듦
arr1[arr2] = 100
print(arr1)

arr1 = np.arange(16).reshape(4,4)
arr1[arr1>10] = 100
print(arr1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]
[[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10 100]
 [100 100 100 100]]


In [ ]:
arr = np.arange(16).reshape(-1,4)
print(f'max : {np.max(arr)}')
print(f'min : {np.min(arr)}')
print(f'mean : {np.mean(arr)}')
print(f'sum : {np.sum(arr)}')
 
#각열에 대해서 모든 행의 원소를 더함
print(arr)
print(np.sum(arr,axis=0))

max : 15
min : 0
mean : 7.5
sum : 120
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 28 32 36]


In [ ]:
#단일 객체 저장 및 불러오기
arr = np.arange(10)
np.save('saved.npy',arr)

In [ ]:
result = np.load('saved.npy')

In [ ]:
result

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#복수 객체 저장 및 불러오기
arr1 = np.arange(10)
arr2 = np.arange(10,20)
np.savez('saved.npz',array1=arr1,array2=arr2)

In [ ]:
result = np.load('saved.npz')
r1 = result['array1']
r2 = result['array2']

In [ ]:
r1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#오름차순
arr = np.array([5,9,10,3,1])
arr.sort()
print(arr)

#내림차순
arr = np.array([5,9,10,3,1])
arr.sort()
print(arr[::-1])

[ 1  3  5  9 10]
[10  9  5  3  1]
[ 1  3  5  9 10]


In [4]:
import numpy as np
import torch

In [6]:
t = np.array([0,1,2,3,4,5,6],dtype=float)
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [8]:
print(t.ndim, t.shape)

1 (7,)


In [14]:
print(t[0], t[-1])
print(t[2:5], t[4:-1], t[:2])

0.0 6.0
[2. 3. 4.] [4. 5.] [0. 1.]


In [18]:
t = np.arange(1,13,dtype=float).reshape(-1,3)

In [19]:
t

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [23]:
# torch 형태로
t = torch.FloatTensor([0,1,2,3,4,5,6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [24]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[-2])

1
torch.Size([7])
torch.Size([7])
tensor(5.)


In [26]:
t = torch.FloatTensor([[1,2,3],
                       [4,5,5],
                       [7,8,9],
                       [10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  5.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [30]:
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1]) #마지막 줄 빼고 모두 가져오기

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [31]:
print(t+3)

tensor([[ 4.,  5.,  6.],
        [ 7.,  8.,  8.],
        [10., 11., 12.],
        [13., 14., 15.]])


In [38]:
print('-'*30)
print('matmul')
print('-'*30)
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.matmul(m2))
# print(m2.matmul(m1)) #error
print()
print('-'*30)
print('mul')
print('-'*30)
print(m1.mul(m2))
print(m2.mul(m1))

------------------------------
matmul
------------------------------
tensor([[ 5.],
        [11.]])

------------------------------
mul
------------------------------
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [39]:
t = torch.FloatTensor([1,2])
t.mean()

tensor(1.5000)

In [40]:
# integer에는 mean 사용불가
t = torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [42]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [45]:
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [46]:
print(t.sum())
print(t.sum(dim=0))

tensor(10.)
tensor([4., 6.])


In [51]:
t = torch.FloatTensor([[1,2],[3,4],[5,3]])
print(t)

print(t.max()) 

print(t.max(dim=0))
print(t.max(dim=0)[0])

print(t.max(dim=1))
print(t.max(dim=1)[0])

tensor([[1., 2.],
        [3., 4.],
        [5., 3.]])
tensor(5.)
torch.return_types.max(
values=tensor([5., 4.]),
indices=tensor([2, 1]))
tensor([5., 4.])
torch.return_types.max(
values=tensor([2., 4., 5.]),
indices=tensor([1, 1, 0]))
tensor([2., 4., 5.])


In [89]:
t = torch.FloatTensor([[[1,2,10],
                        [24,5,6],
                        [1,2,3]],
                       [[17,8,9],
                        [10,11,12],
                        [50,0,1]]])
print(t)

tensor([[[ 1.,  2., 10.],
         [24.,  5.,  6.],
         [ 1.,  2.,  3.]],

        [[17.,  8.,  9.],
         [10., 11., 12.],
         [50.,  0.,  1.]]])


In [92]:
print(t.max())

tensor(50.)


In [94]:

print(t.max(dim=2)[0])

tensor([[10., 24.,  3.],
        [17., 12., 50.]])


In [74]:
t = torch.FloatTensor([[1,2,3],
                        [4,5,6],
                       [0,8,7]])
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [0., 8., 7.]])

In [76]:
print(t.max(dim=0)[0])
print(t.max(dim=1)[0])

tensor([4., 8., 7.])
tensor([3., 6., 8.])


# view

In [99]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print(ft)

torch.Size([2, 2, 3])
tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])


In [100]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [101]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


# squeeze

In [102]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [103]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


# unsqueeze
1인 차원 생성 - > 어느차원에 1인 차원 생성할지 지정해주기

In [107]:
ft = torch.tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [108]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0, 1, 2]])
torch.Size([1, 3])


In [109]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0, 1, 2]])
torch.Size([1, 3])


In [110]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


In [111]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0],
        [1],
        [2]])
torch.Size([3, 1])


In [113]:
 lt = torch.LongTensor([1,2,3,4])
 print(lt)

tensor([1, 2, 3, 4])


In [114]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [115]:
bt = (lt==3)

In [116]:
bt

tensor([False, False,  True, False])

In [119]:
bt = torch.ByteTensor([True,False,False,True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [121]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# concatebate

In [122]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [123]:
print(torch.cat([x,y],dim=0))
print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# stacking

In [124]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [125]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [126]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# ones and zeros

In [127]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [134]:
print(torch.ones_like(x).long())
print(torch.zeros_like(x))

tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


# in place option

In [136]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
tensor([[0., 2., 4.],
        [4., 2., 0.]])
